### ISSUE TITLE
base dataset python file is missing

### ISSUE THREAD

**Issue by tjdhg456** [lsa1997/POP#1]
Hi! Thank you for your great work.

In the "dataset folder/voc.py", It loads the "BaseDataset" class from the "dataset_folder/base_dataset.py".
However, from the github, base_dataset.py does not exist.
Can you share its code?

Also, Can you upload the base training code for COCO along with the dataset loading part?

Thank you.

**Comment by lsa1997** [comment]
Hi, thanks for your interest in our work! I accidentally left out a few files while uploading the code. I have now rectified the issue and uploaded the missing files. Sorry for the inconvenience. I hope that this helps you in your work.

**Comment by tjdhg456** [comment]
Hi!

Thank you for your fast response and look forward to see your work on CVPR 2023.

Thank you.
