### ISSUE TITLE
about pretained models

### ISSUE THREAD

**Issue by WXWlife** [lsa1997/POP#3]
Hi! Thank you for your great work.
I cann't  download ImageNet pretained ResNet-50 from PFENet using the link
Can you provide the download address
Thank you

**Comment by lsa1997** [comment]
Try [this link](https://mycuhk-my.sharepoint.com/:u:/g/personal/1155122171_link_cuhk_edu_hk/EQEY0JxITwVHisdVzusEqNUBNsf1CT8MsALdahUhaHrhlw?e=4%3a2o3XTL&at=9).

**Comment by WXWlife** [comment]
Thank you for your prompt reply, I'll give it a try
